filter:
    excluded_paths:
        - 'assets/*'
        - 'languages/*'
        - 'node_modules/*'
        - 'tests/*'
        - 'vendor/*'
before_commands:
    - 'composer install --dev --prefer-source'
checks:
    php:
        no_exit: false
        no_global_keyword: false
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        simplify_boolean_return: true
        prefer_while_loop_over_for_loop: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        encourage_single_quotes: true
        avoid_todo_comments: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        psr2_switch_declaration: false
    javascript:
        no_else_return: true
        eqeqeq: true
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            before_parentheses:
                if: false
                for: false
                while: false
                switch: false
                catch: false
            around_operators:
                concatenation: true
            within:
                brackets: true
                array_initializer: true
                grouping: true
                function_call: true
                function_declaration: true
                if: true
                for: true
                while: true
                switch: true
                catch: true
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: new-line
            if:
                else_on_new_line: true
            do_while:
                while_on_new_line: true
            try:
                catch_on_new_line: true
                finally_on_new_line: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower
build:
    environment:
        php: '7.1.0'
        node: '5.1.0'
    project_setup:
        before:
            - 'bash tests/bin/install.sh wordpress_test root "" localhost $WP_VERSION'
            - 'bash tests/bin/travis.sh before'
    tests:
        override:
            -  jshint-run
            -
                command: 'phpunit --coverage-clover=tests/clover.xml'
                coverage:
                    file: 'tests/clover.xml'
                    format: 'clover'

